# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-14 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_tracking_url', models.CharField(help_text='URL where piwik.php is located.', max_length=255, verbose_name='Tracking base URL')),
                ('pk_site_id', models.IntegerField(help_text='Id of site as assigned by Piwik (see Piwik Websites page).', verbose_name='Piwik site ID')),
                ('site', models.OneToOneField(help_text='Django site', on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'ordering': ['site'],
                'verbose_name_plural': 'Analytics',
            },
        ),
    ]
